server:
  port: 8080

spring:
  application:
    name: MySpringBootApp

  datasource:
    url: jdbc:postgresql://localhost:5432/nama_database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        web: DEBUG
